DROP SCHEMA IF EXISTS "store" CASCADE;

CREATE SCHEMA "store";

CREATE TYPE "software_categories" AS ENUM (
  'os',
  'vr',
  'business',
  'education',
  'finance',
  'design',
  'kids',
  'magazines',
  'music',
  'news',
  'productivity',
  'browser_extension',
  'social_networking',
  'travel',
  'books',
  'developer_tools',
  'entertainment',
  'food_drink',
  'health',
  'lifestyle',
  'medical',
  'navigation',
  'media',
  'shopping',
  'sports',
  'utilities'
);

CREATE TYPE "user_types" AS ENUM (
  'individual',
  'corporate',
  'joint',
  'group'
);

CREATE TYPE "user_applications" AS ENUM (
  'default',
  'business',
  'finance',
  'healthcare',
  'education',
  'logistics',
  'entertainment',
  'social',
  'trading'
);

CREATE TYPE "languages" AS ENUM (
  'english',
  'russian',
  'chinese',
  'portuguese',
  'german',
  'japanese',
  'turkish',
  'french',
  'hindi',
  'spanish',
  'arabic'
);

CREATE TABLE "store"."countries" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "language" languages NOT NULL
);

CREATE TABLE "store"."softwares" (
  "id" uuid PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "description" text NOT NULL,
  "category" software_categories NOT NULL,
  "tags" varchar[] NOT NULL,
  "version" varchar NOT NULL,
  "release_date" date NOT NULL,
  "license_price" integer NOT NULL,
  "migration_price" integer
);

CREATE TABLE "store"."users" (
  "id" uuid PRIMARY KEY,
  "username" varchar UNIQUE NOT NULL,
  "country" integer NOT NULL,
  "user_type" user_types NOT NULL,
  "application" user_applications NULL
);

CREATE TABLE "store"."purchase_history" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "software_id" uuid NOT NULL,
  "price" integer NOT NULL,
  "purchase_date" date NOT NULL
);

CREATE TABLE "store"."reviews" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "software_id" uuid NOT NULL,
  "rating" integer NOT NULL,
  "review_content" jsonb NOT NULL,
  "review_date" date NOT NULL
);

ALTER TABLE "store"."users" ADD FOREIGN KEY ("country") REFERENCES "countries" ("id") ON DELETE CASCADE;
ALTER TABLE "store"."purchase_history" ADD FOREIGN KEY ("user_id") REFERENCES "store"."users" ("id") ON DELETE CASCADE;
ALTER TABLE "store"."purchase_history" ADD FOREIGN KEY ("software_id") REFERENCES "store"."softwares" ("id") ON DELETE CASCADE;
ALTER TABLE "store"."reviews" ADD FOREIGN KEY ("user_id") REFERENCES "store"."users" ("id") ON DELETE CASCADE;
ALTER TABLE "store"."reviews" ADD FOREIGN KEY ("software_id") REFERENCES "store"."softwares" ("id") ON DELETE CASCADE;

CREATE INDEX idx_category ON "store"."softwares" ("category");
CREATE UNIQUE INDEX idx_name ON "store"."softwares" ("name");
CREATE INDEX idx_reviews_software_id ON "store"."reviews" ("software_id");
