-- READ UNCOMMITTED, READ COMMITTED, REPEATABLE READ, SERIALIZABLE
BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE;

UPDATE store.softwares
SET license_price = ROUND(license_price * 1.1)
WHERE id = '5a50ed1a-9f98-4a69-a93d-dd196af1fcb2';

COMMIT;
